# Generated by Django 4.2.16 on 2025-10-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_load_specialized_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(db_column='requester_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_requester', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(db_column='responder_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_responder', to=settings.AUTH_USER_MODEL)),
                ('trade_request', models.ForeignKey(db_column='tradereq_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.traderequest')),
            ],
            options={
                'db_table': 'conversations_tbl',
                'managed': True,
                'unique_together': {('trade_request',)},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages_tbl',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
