# Generated by Django 4.2.16 on 2025-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedetail',
            name='contextpic',
            field=models.TextField(blank=True, db_column='contextpic', null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='requester_proof',
            field=models.TextField(blank=True, db_column='requester_proof', null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='responder_proof',
            field=models.TextField(blank=True, db_column='responder_proof', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.TextField(blank=True, db_column='profilepic', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userVerifyId',
            field=models.TextField(blank=True, db_column='userverifyid', null=True),
        ),
    ]
