# Generated by Django 4.2.16 on 2025-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_email', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_desc', models.TextField(blank=True, null=True)),
                ('ticket_pic', models.TextField(blank=True, null=True)),
                ('ticket_datesubmitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supptix_tbl',
                'managed': False,
            },
        ),
    ]
