# Generated by Django 4.2.16 on 2025-10-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supportticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={},
        ),
    ]
