# Generated by Django 4.2.16 on 2025-10-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_supportticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
