# Generated by Django 4.2.16 on 2025-10-12 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_supportticket_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='DeletedConversation',
            fields=[
                ('deleted_conversation_id', models.AutoField(db_column='deleted_conversation_id', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_column='deleted_at')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_users', to='accounts.conversation')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deleted_conversations_tbl',
                'managed': True,
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
