# Generated by Django 4.2.16 on 2025-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_supportticket_options_deletedconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='requester_proof',
            field=models.JSONField(blank=True, db_column='requester_proof', default=list, help_text='Array of proof objects: [{"type": "file", "url": "cloudinary_url"}, {"type": "link", "url": "external_link"}]', null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='responder_proof',
            field=models.JSONField(blank=True, db_column='responder_proof', default=list, help_text='Array of proof objects: [{"type": "file", "url": "cloudinary_url"}, {"type": "link", "url": "external_link"}]', null=True),
        ),
    ]
