# Generated by Django 4.2.16 on 2025-10-14 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_evaluation_trade_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('device_id', models.AutoField(db_column='device_id', primary_key=True, serialize=False)),
                ('device_token', models.CharField(db_column='device_token', max_length=64, unique=True)),
                ('device_name', models.CharField(db_column='device_name', help_text='e.g., Chrome 120 on Windows 10', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True)),
                ('user_agent', models.TextField(blank=True, db_column='user_agent', null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, db_column='last_used_at')),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_devices_tbl',
                'managed': True,
            },
        ),
    ]
