# Generated by Django 4.2.16 on 2025-10-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_trusteddevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustedDevice',
        ),
    ]
