# Generated by Django 4.2.16 on 2025-10-21 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_trusteddevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userVerifyId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('verification_id', models.AutoField(db_column='verification_id', primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(db_column='email_verified', default=False)),
                ('email_verification_token', models.CharField(blank=True, db_column='email_verification_token', max_length=64, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, db_column='email_verified_at', null=True)),
                ('id_document', models.TextField(blank=True, db_column='id_link', null=True)),
                ('id_type', models.CharField(db_column='id_type', max_length=100)),
                ('id_verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_column='id_verification_status', default='UNVERIFIED', max_length=20)),
                ('id_submitted_at', models.DateTimeField(blank=True, db_column='id_submitted_at', null=True)),
                ('id_verified_at', models.DateTimeField(blank=True, db_column='id_verified_at', null=True)),
                ('rejection_reason', models.TextField(blank=True, db_column='rejection_reason', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_column='rejected_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_verification_tbl',
                'managed': True,
            },
        ),
    ]
