# Generated by Django 4.2.16 on 2025-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_is_verified_remove_user_userverifyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='userverification',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, db_column='email_otp_created_at', null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='email_verification_otp',
            field=models.CharField(blank=True, db_column='email_verification_otp', max_length=7, null=True),
        ),
    ]
