# Generated by Django 4.2.16 on 2025-11-03 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_birthdate_user_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TRADE_INTEREST', 'Trade Interest'), ('TRADE_ACCEPTED', 'Trade Accepted'), ('TRADE_CONFIRMED', 'Trade Confirmed'), ('PROOF_SUBMITTED', 'Proof Submitted'), ('PROOF_APPROVED', 'Proof Approved'), ('VERIF_ACCEPTED', 'Verification Accepted'), ('VERIF_REJECTED', 'Verification Rejected')], default='TRADE_INTEREST', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_tbl',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
