# Generated by Django 4.2.16 on 2025-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sanction_details',
            field=models.JSONField(blank=True, db_column='sanction_details', default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sanction_status',
            field=models.CharField(choices=[('NONE', 'No Sanction'), ('WARNING', 'Warning'), ('SUSPENSION', 'Suspension'), ('BAN', 'Permanent Ban')], db_column='sanction_status', default='NONE', max_length=20),
        ),
    ]
