# Generated by Django 4.2.16 on 2025-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='appeal_status',
            field=models.CharField(choices=[('NONE', 'No Appeal Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_column='appeal_status', default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='sanction_applied',
            field=models.CharField(choices=[('NONE', 'No Sanction'), ('WARNING', 'Warning'), ('SUSPENSION', 'Suspension'), ('BAN', 'Permanent Ban'), ('DISMISS', 'Dismissed')], db_column='sanction_applied', default='DISMISS', max_length=20),
        ),
    ]
