# Generated by Django 4.2.16 on 2025-11-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_report_appeal_status_report_sanction_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='appeal_details',
            field=models.JSONField(blank=True, db_column='appeal_details', default=dict, null=True),
        ),
    ]
