# Generated by Django 5.2.8 on 2025-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_report_admin_reviewer_report_appeal_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredential',
            name='genskills_id',
        ),
        migrations.RemoveField(
            model_name='usercredential',
            name='specskills_id',
        ),
        migrations.AddField(
            model_name='usercredential',
            name='general_category_name',
            field=models.CharField(blank=True, db_column='general_category_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='specific_skill_names',
            field=models.JSONField(blank=True, db_column='specific_skill_names', default=list, null=True),
        ),
    ]
