--
-- PostgreSQL database dump
--

\restrict zSO8M3vyU612OsLEH32xf7dgYrr2RWa2QUplclEJK4V1YAqoJUbaVm00jf8nyAe

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: interest_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.interest_status AS ENUM (
    'PENDING',
    'ACCEPTED',
    'DECLINED'
);


ALTER TYPE public.interest_status OWNER TO postgres;

--
-- Name: model_delivery; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.model_delivery AS ENUM (
    'Onsite',
    'Online (synchronous)',
    'Online (asynchronous)',
    'Hybrid'
);


ALTER TYPE public.model_delivery OWNER TO postgres;

--
-- Name: request_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.request_type AS ENUM (
    'Service',
    'Output',
    'Project'
);


ALTER TYPE public.request_type OWNER TO postgres;

--
-- Name: verification_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.verification_status AS ENUM (
    'UNVERIFIED',
    'PENDING',
    'VERIFIED',
    'REJECTED'
);


ALTER TYPE public.verification_status OWNER TO postgres;

--
-- Name: xp_rank; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.xp_rank AS ENUM (
    'Unranked',
    'Dwarf Star',
    'Rising Star',
    'Shining Star',
    'Giant',
    'Supergiant',
    'Stellar',
    'Radiant',
    'Cosmic',
    'Luminary',
    'Ethereal',
    'Celestial'
);


ALTER TYPE public.xp_rank OWNER TO postgres;

--
-- Name: sync_is_verified_from_status(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.sync_is_verified_from_status() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      NEW.is_verified := (NEW.verification_status = 'VERIFIED');
      RETURN NEW;
    END
    $$;


ALTER FUNCTION public.sync_is_verified_from_status() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversations_tbl (
    conversation_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    requester_id integer NOT NULL,
    responder_id integer NOT NULL,
    tradereq_id integer NOT NULL
);


ALTER TABLE public.conversations_tbl OWNER TO postgres;

--
-- Name: conversations_tbl_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conversations_tbl ALTER COLUMN conversation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_tbl_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: evaluation_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluation_tbl (
    evaluation_id integer NOT NULL,
    tradereq_id integer NOT NULL,
    taskcomplexity integer,
    timecommitment integer,
    skilllevel integer,
    evaluationdescription character varying(500),
    requester_evaluation_status character varying(20),
    responder_evaluation_status character varying(20),
    requester_responded_at timestamp without time zone,
    responder_responded_at timestamp without time zone,
    CONSTRAINT check_requester_evaluation_status CHECK (((requester_evaluation_status)::text = ANY (ARRAY[('CONFIRMED'::character varying)::text, ('REJECTED'::character varying)::text]))),
    CONSTRAINT check_responder_evaluation_status CHECK (((responder_evaluation_status)::text = ANY (ARRAY[('CONFIRMED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


ALTER TABLE public.evaluation_tbl OWNER TO postgres;

--
-- Name: evaluation_tbl_evaluation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.evaluation_tbl_evaluation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.evaluation_tbl_evaluation_id_seq OWNER TO postgres;

--
-- Name: evaluation_tbl_evaluation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.evaluation_tbl_evaluation_id_seq OWNED BY public.evaluation_tbl.evaluation_id;


--
-- Name: genskills_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genskills_tbl (
    genskills_id integer NOT NULL,
    gencateg character varying(100)
);


ALTER TABLE public.genskills_tbl OWNER TO postgres;

--
-- Name: genskills_tbl_genskills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.genskills_tbl_genskills_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.genskills_tbl_genskills_id_seq OWNER TO postgres;

--
-- Name: genskills_tbl_genskills_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.genskills_tbl_genskills_id_seq OWNED BY public.genskills_tbl.genskills_id;


--
-- Name: messages_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages_tbl (
    message_id integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    conversation_id integer NOT NULL,
    sender_id integer NOT NULL
);


ALTER TABLE public.messages_tbl OWNER TO postgres;

--
-- Name: messages_tbl_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages_tbl ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_tbl_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_token_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_token_tbl (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.password_reset_token_tbl OWNER TO postgres;

--
-- Name: password_reset_token_tbl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.password_reset_token_tbl_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.password_reset_token_tbl_id_seq OWNER TO postgres;

--
-- Name: password_reset_token_tbl_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.password_reset_token_tbl_id_seq OWNED BY public.password_reset_token_tbl.id;


--
-- Name: reports_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports_tbl (
    report_id integer NOT NULL,
    category character varying(100) NOT NULL,
    issue_detail character varying(255) NOT NULL,
    description text,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reported_user_id integer,
    reporter_id integer NOT NULL,
    tradereq_id integer
);


ALTER TABLE public.reports_tbl OWNER TO postgres;

--
-- Name: reports_tbl_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports_tbl ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_tbl_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repsys_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.repsys_tbl (
    repsys_id integer NOT NULL,
    tradereq_id integer,
    requester_starcount integer,
    responder_starcount integer,
    requester_rating_desc character varying(500),
    responder_rating_desc character varying(500),
    requester_rated_at timestamp without time zone,
    responder_rated_at timestamp without time zone,
    CONSTRAINT repsys_tbl_requester_starcount_check CHECK (((requester_starcount >= 0) AND (requester_starcount <= 5)))
);


ALTER TABLE public.repsys_tbl OWNER TO postgres;

--
-- Name: repsys_tbl_repsys_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.repsys_tbl_repsys_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.repsys_tbl_repsys_id_seq OWNER TO postgres;

--
-- Name: repsys_tbl_repsys_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.repsys_tbl_repsys_id_seq OWNED BY public.repsys_tbl.repsys_id;


--
-- Name: specskills_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specskills_tbl (
    specskills_id integer NOT NULL,
    genskills_id integer,
    speccateg character varying(100)
);


ALTER TABLE public.specskills_tbl OWNER TO postgres;

--
-- Name: specskills_tbl_specskills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.specskills_tbl_specskills_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.specskills_tbl_specskills_id_seq OWNER TO postgres;

--
-- Name: specskills_tbl_specskills_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.specskills_tbl_specskills_id_seq OWNED BY public.specskills_tbl.specskills_id;


--
-- Name: supptix_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supptix_tbl (
    ticket_id integer NOT NULL,
    user_id integer,
    ticket_name character varying(100),
    ticket_email character varying(100),
    ticket_title character varying(100),
    ticket_desc text,
    ticket_pic text,
    ticket_datesubmitted timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.supptix_tbl OWNER TO postgres;

--
-- Name: supptix_tbl_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.supptix_tbl_ticket_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.supptix_tbl_ticket_id_seq OWNER TO postgres;

--
-- Name: supptix_tbl_ticket_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.supptix_tbl_ticket_id_seq OWNED BY public.supptix_tbl.ticket_id;


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO postgres;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trade_details_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trade_details_tbl (
    tradedetails_id integer NOT NULL,
    tradereq_id integer NOT NULL,
    user_id integer NOT NULL,
    skillprof character varying(13),
    modedel character varying(25),
    reqtype character varying(35),
    contextpic text,
    reqbio character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total_xp integer
);


ALTER TABLE public.trade_details_tbl OWNER TO postgres;

--
-- Name: trade_details_tbl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trade_details_tbl_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.trade_details_tbl_id_seq OWNER TO postgres;

--
-- Name: trade_details_tbl_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trade_details_tbl_id_seq OWNED BY public.trade_details_tbl.tradedetails_id;


--
-- Name: trade_interests_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trade_interests_tbl (
    trade_interests_id integer NOT NULL,
    tradereq_id integer NOT NULL,
    interested_user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    status character varying(15) DEFAULT 'PENDING'::public.interest_status NOT NULL,
    CONSTRAINT check_status CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('ACCEPTED'::character varying)::text, ('DECLINED'::character varying)::text, ('CANCELLED'::character varying)::text])))
);


ALTER TABLE public.trade_interests_tbl OWNER TO postgres;

--
-- Name: TABLE trade_interests_tbl; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.trade_interests_tbl IS 'Tracks users who expressed interest in trade requests';


--
-- Name: trade_interests_tbl_trade_interests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trade_interests_tbl ALTER COLUMN trade_interests_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trade_interests_tbl_trade_interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tradehis_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tradehis_tbl (
    tradehis_id integer NOT NULL,
    tradereq_id integer,
    completed_at timestamp with time zone,
    requester_proof text,
    responder_proof text,
    requester_proof_status character varying(20) DEFAULT 'PENDING'::character varying,
    responder_proof_status character varying(20) DEFAULT 'PENDING'::character varying,
    CONSTRAINT tradehis_tbl_requester_proof_status_check CHECK (((requester_proof_status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text]))),
    CONSTRAINT tradehis_tbl_responder_proof_status_check CHECK (((responder_proof_status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


ALTER TABLE public.tradehis_tbl OWNER TO postgres;

--
-- Name: tradehis_tbl_tradehis_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tradehis_tbl_tradehis_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tradehis_tbl_tradehis_id_seq OWNER TO postgres;

--
-- Name: tradehis_tbl_tradehis_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tradehis_tbl_tradehis_id_seq OWNED BY public.tradehis_tbl.tradehis_id;


--
-- Name: tradereq_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tradereq_tbl (
    tradereq_id integer NOT NULL,
    requester_id integer,
    responder_id integer,
    reqname character varying(255),
    reqdeadline date,
    status character varying(15),
    exchangename character varying(255),
    classifiedcategory character varying(100),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    requester_rated boolean DEFAULT false,
    responder_rated boolean DEFAULT false
);


ALTER TABLE public.tradereq_tbl OWNER TO postgres;

--
-- Name: tradereq_tbl_tradereq_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tradereq_tbl_tradereq_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tradereq_tbl_tradereq_id_seq OWNER TO postgres;

--
-- Name: tradereq_tbl_tradereq_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tradereq_tbl_tradereq_id_seq OWNED BY public.tradereq_tbl.tradereq_id;


--
-- Name: usercredentials_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usercredentials_tbl (
    usercred_id integer NOT NULL,
    user_id integer NOT NULL,
    credential_title character varying(150),
    issuer character varying(150),
    issue_date date,
    expiry_date date,
    cred_id character varying(100),
    cred_url text,
    genskills_id integer,
    specskills_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.usercredentials_tbl OWNER TO postgres;

--
-- Name: usercerts_tbl_cert_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usercerts_tbl_cert_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usercerts_tbl_cert_id_seq OWNER TO postgres;

--
-- Name: usercerts_tbl_cert_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usercerts_tbl_cert_id_seq OWNED BY public.usercredentials_tbl.usercred_id;


--
-- Name: userinterests_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.userinterests_tbl (
    userinterests_id integer NOT NULL,
    user_id integer NOT NULL,
    genskills_id integer NOT NULL
);


ALTER TABLE public.userinterests_tbl OWNER TO postgres;

--
-- Name: userinterests_tbl_usergeninterests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.userinterests_tbl_usergeninterests_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.userinterests_tbl_usergeninterests_id_seq OWNER TO postgres;

--
-- Name: userinterests_tbl_usergeninterests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.userinterests_tbl_usergeninterests_id_seq OWNED BY public.userinterests_tbl.userinterests_id;


--
-- Name: users_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_tbl (
    user_id integer NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    username character varying(50),
    email character varying(50),
    password character varying(100),
    profilepic text,
    bio character varying(150),
    location character varying(300),
    ratingcount integer DEFAULT 0,
    avgstars numeric(3,2) DEFAULT 0.00,
    tot_xppts integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    userverifyid text,
    links text,
    level integer DEFAULT 1 NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    verification_status public.verification_status DEFAULT 'UNVERIFIED'::public.verification_status NOT NULL,
    is_active boolean DEFAULT true
);


ALTER TABLE public.users_tbl OWNER TO postgres;

--
-- Name: users_tbl_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_tbl_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_tbl_user_id_seq OWNER TO postgres;

--
-- Name: users_tbl_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_tbl_user_id_seq OWNED BY public.users_tbl.user_id;


--
-- Name: userskills_tbl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.userskills_tbl (
    userskills_id integer NOT NULL,
    user_id integer,
    specskills_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.userskills_tbl OWNER TO postgres;

--
-- Name: userskills_tbl_userskills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.userskills_tbl_userskills_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.userskills_tbl_userskills_id_seq OWNER TO postgres;

--
-- Name: userskills_tbl_userskills_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.userskills_tbl_userskills_id_seq OWNED BY public.userskills_tbl.userskills_id;


--
-- Name: evaluation_tbl evaluation_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_tbl ALTER COLUMN evaluation_id SET DEFAULT nextval('public.evaluation_tbl_evaluation_id_seq'::regclass);


--
-- Name: genskills_tbl genskills_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genskills_tbl ALTER COLUMN genskills_id SET DEFAULT nextval('public.genskills_tbl_genskills_id_seq'::regclass);


--
-- Name: password_reset_token_tbl id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token_tbl ALTER COLUMN id SET DEFAULT nextval('public.password_reset_token_tbl_id_seq'::regclass);


--
-- Name: repsys_tbl repsys_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repsys_tbl ALTER COLUMN repsys_id SET DEFAULT nextval('public.repsys_tbl_repsys_id_seq'::regclass);


--
-- Name: specskills_tbl specskills_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specskills_tbl ALTER COLUMN specskills_id SET DEFAULT nextval('public.specskills_tbl_specskills_id_seq'::regclass);


--
-- Name: supptix_tbl ticket_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supptix_tbl ALTER COLUMN ticket_id SET DEFAULT nextval('public.supptix_tbl_ticket_id_seq'::regclass);


--
-- Name: trade_details_tbl tradedetails_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_details_tbl ALTER COLUMN tradedetails_id SET DEFAULT nextval('public.trade_details_tbl_id_seq'::regclass);


--
-- Name: tradehis_tbl tradehis_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradehis_tbl ALTER COLUMN tradehis_id SET DEFAULT nextval('public.tradehis_tbl_tradehis_id_seq'::regclass);


--
-- Name: tradereq_tbl tradereq_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradereq_tbl ALTER COLUMN tradereq_id SET DEFAULT nextval('public.tradereq_tbl_tradereq_id_seq'::regclass);


--
-- Name: usercredentials_tbl usercred_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usercredentials_tbl ALTER COLUMN usercred_id SET DEFAULT nextval('public.usercerts_tbl_cert_id_seq'::regclass);


--
-- Name: userinterests_tbl userinterests_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterests_tbl ALTER COLUMN userinterests_id SET DEFAULT nextval('public.userinterests_tbl_usergeninterests_id_seq'::regclass);


--
-- Name: users_tbl user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tbl ALTER COLUMN user_id SET DEFAULT nextval('public.users_tbl_user_id_seq'::regclass);


--
-- Name: userskills_tbl userskills_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl ALTER COLUMN userskills_id SET DEFAULT nextval('public.userskills_tbl_userskills_id_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add gen skill	8	add_genskill
30	Can change gen skill	8	change_genskill
31	Can delete gen skill	8	delete_genskill
32	Can view gen skill	8	view_genskill
33	Can add spec skill	9	add_specskill
34	Can change spec skill	9	change_specskill
35	Can delete spec skill	9	delete_specskill
36	Can view spec skill	9	view_specskill
37	Can add user credential	10	add_usercredential
38	Can change user credential	10	change_usercredential
39	Can delete user credential	10	delete_usercredential
40	Can view user credential	10	view_usercredential
41	Can add user interest	11	add_userinterest
42	Can change user interest	11	change_userinterest
43	Can delete user interest	11	delete_userinterest
44	Can view user interest	11	view_userinterest
45	Can add user skill	12	add_userskill
46	Can change user skill	12	change_userskill
47	Can delete user skill	12	delete_userskill
48	Can view user skill	12	view_userskill
49	Can add Blacklisted Token	13	add_blacklistedtoken
50	Can change Blacklisted Token	13	change_blacklistedtoken
51	Can delete Blacklisted Token	13	delete_blacklistedtoken
52	Can view Blacklisted Token	13	view_blacklistedtoken
53	Can add Outstanding Token	14	add_outstandingtoken
54	Can change Outstanding Token	14	change_outstandingtoken
55	Can delete Outstanding Token	14	delete_outstandingtoken
56	Can view Outstanding Token	14	view_outstandingtoken
57	Can add trade request	15	add_traderequest
58	Can change trade request	15	change_traderequest
59	Can delete trade request	15	delete_traderequest
60	Can view trade request	15	view_traderequest
61	Can add trade interest	16	add_tradeinterest
62	Can change trade interest	16	change_tradeinterest
63	Can delete trade interest	16	delete_tradeinterest
64	Can view trade interest	16	view_tradeinterest
65	Can add trade detail	17	add_tradedetail
66	Can change trade detail	17	change_tradedetail
67	Can delete trade detail	17	delete_tradedetail
68	Can view trade detail	17	view_tradedetail
69	Can add evaluation	18	add_evaluation
70	Can change evaluation	18	change_evaluation
71	Can delete evaluation	18	delete_evaluation
72	Can view evaluation	18	view_evaluation
73	Can add trade history	19	add_tradehistory
74	Can change trade history	19	change_tradehistory
75	Can delete trade history	19	delete_tradehistory
76	Can view trade history	19	view_tradehistory
77	Can add password reset token	20	add_passwordresettoken
78	Can change password reset token	20	change_passwordresettoken
79	Can delete password reset token	20	delete_passwordresettoken
80	Can view password reset token	20	view_passwordresettoken
81	Can add reputation system	21	add_reputationsystem
82	Can change reputation system	21	change_reputationsystem
83	Can delete reputation system	21	delete_reputationsystem
84	Can view reputation system	21	view_reputationsystem
85	Can add message	22	add_message
86	Can change message	22	change_message
87	Can delete message	22	delete_message
88	Can view message	22	view_message
89	Can add conversation	23	add_conversation
90	Can change conversation	23	change_conversation
91	Can delete conversation	23	delete_conversation
92	Can view conversation	23	view_conversation
93	Can add report	24	add_report
94	Can change report	24	change_report
95	Can delete report	24	delete_report
96	Can view report	24	view_report
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: conversations_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.conversations_tbl (conversation_id, created_at, requester_id, responder_id, tradereq_id) FROM stdin;
1	2025-10-12 02:48:08.398168+08	5	2	4
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounts	user
8	accounts	genskill
9	accounts	specskill
10	accounts	usercredential
11	accounts	userinterest
12	accounts	userskill
13	token_blacklist	blacklistedtoken
14	token_blacklist	outstandingtoken
15	accounts	traderequest
16	accounts	tradeinterest
17	accounts	tradedetail
18	accounts	evaluation
19	accounts	tradehistory
20	accounts	passwordresettoken
21	accounts	reputationsystem
22	accounts	message
23	accounts	conversation
24	accounts	report
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-07-30 04:42:51.904435+08
2	auth	0001_initial	2025-07-30 04:42:52.030999+08
6	contenttypes	0002_remove_content_type_name	2025-07-30 04:42:52.096073+08
7	auth	0002_alter_permission_name_max_length	2025-07-30 04:42:52.107656+08
8	auth	0003_alter_user_email_max_length	2025-07-30 04:42:52.116667+08
9	auth	0004_alter_user_username_opts	2025-07-30 04:42:52.125487+08
10	auth	0005_alter_user_last_login_null	2025-07-30 04:42:52.13595+08
11	auth	0006_require_contenttypes_0002	2025-07-30 04:42:52.137861+08
12	auth	0007_alter_validators_add_error_messages	2025-07-30 04:42:52.145508+08
13	auth	0008_alter_user_username_max_length	2025-07-30 04:42:52.160082+08
14	auth	0009_alter_user_last_name_max_length	2025-07-30 04:42:52.171157+08
15	auth	0010_alter_group_name_max_length	2025-07-30 04:42:52.178166+08
16	auth	0011_update_proxy_permissions	2025-07-30 04:42:52.186669+08
17	auth	0012_alter_user_first_name_max_length	2025-07-30 04:42:52.193802+08
18	sessions	0001_initial	2025-07-30 04:42:52.209412+08
22	accounts	0002_genskill_specskill_usercredential_userinterest_and_more	2025-09-14 06:16:51.945589+08
23	accounts	0003_alter_user_options_alter_usercredential_options_and_more	2025-09-14 06:22:30.220917+08
24	accounts	0004_usercredential_genskills_id_and_more	2025-09-14 06:54:29.407351+08
25	accounts	0005_user_is_active	2025-09-14 16:33:00.979991+08
41	accounts	0006_alter_user_profilepic_alter_user_userverifyid	2025-09-18 17:49:30.678222+08
42	accounts	0007_traderequest	2025-09-18 18:47:50.332201+08
43	accounts	0008_remove_traderequest_genskills_traderequest_status_and_more	2025-09-20 04:38:39.330327+08
44	accounts	0009_alter_traderequest_status_tradeinterest	2025-09-20 11:52:22.0954+08
45	accounts	0010_tradeinterest_status_alter_traderequest_status_and_more	2025-09-21 15:00:16.538762+08
46	accounts	0011_remove_traderequest_specskills_traderequest_exchange_and_more	2025-09-21 21:28:42.225625+08
47	accounts	0012_remove_traderequest_contextpic_and_more	2025-09-22 03:48:32.690872+08
48	accounts	0013_tradedetail_total_xp	2025-09-22 04:54:45.284594+08
49	accounts	0014_remove_tradedetail_id_tradedetail_tradedetails_id_and_more	2025-09-22 18:07:28.912524+08
50	accounts	0015_evaluation	2025-09-22 22:01:56.231968+08
51	accounts	0016_alter_tradeinterest_options_and_more	2025-09-23 04:11:17.792306+08
52	accounts	0017_evaluation_requester_evaluation_status_and_more	2025-09-23 16:47:03.354197+08
53	accounts	0018_remove_tradeinterest_evaluation_status	2025-09-23 17:05:18.351583+08
54	accounts	0019_traderequest_created_at	2025-09-23 17:29:20.213192+08
55	accounts	0020_remove_evaluation_created_at_remove_evaluation_id_and_more	2025-09-23 17:50:58.083326+08
56	accounts	0021_tradehistory	2025-09-24 00:49:22.008979+08
57	accounts	0022_passwordresettoken_reputationsystem	2025-09-25 22:40:58.994483+08
58	accounts	0023_remove_reputationsystem_rated_at_and_more	2025-09-26 01:52:27.490139+08
59	accounts	0002_alter_usercredential_specskills_id	2025-09-28 02:05:46.575902+08
60	accounts	0024_alter_usercredential_specskills_id	2025-09-30 21:27:57.688847+08
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: evaluation_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluation_tbl (evaluation_id, tradereq_id, taskcomplexity, timecommitment, skilllevel, evaluationdescription, requester_evaluation_status, responder_evaluation_status, requester_responded_at, responder_responded_at) FROM stdin;
\.


--
-- Data for Name: genskills_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.genskills_tbl (genskills_id, gencateg) FROM stdin;
1	Creative & Design
2	Technical & IT
3	Business & Management
4	Communication & Interpersonal
5	Health & Wellness
6	Education & Training
7	Home & Lifestyle
8	Handiwork & Maintenance
9	Digital & Social Media
10	Language & Translation
11	Financial & Accounting
12	Sports & Fitness
13	Arts & Performance
14	Culture & Diversity
15	Research & Critical Thinking
\.


--
-- Data for Name: messages_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages_tbl (message_id, content, created_at, conversation_id, sender_id) FROM stdin;
1	hi beh	2025-10-12 03:09:49.100636+08	1	5
\.


--
-- Data for Name: password_reset_token_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_token_tbl (id, user_id, token, created_at, expires_at) FROM stdin;
\.


--
-- Data for Name: reports_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reports_tbl (report_id, category, issue_detail, description, status, created_at, reported_user_id, reporter_id, tradereq_id) FROM stdin;
1	Trade Issues	Did not deliver promised service	wala naman binigay nung dulo na hayz	Pending	2025-10-12 05:12:29.352591+08	3	5	5
2	Trade Issues	Did not deliver promised service	inaaway ako ni beh	Pending	2025-10-12 05:14:49.405988+08	3	5	5
3	User Behavior	Disrespectful or rude language	minumura mura ako teh	Pending	2025-10-12 05:19:29.433283+08	3	5	5
4	User Behavior	Disrespectful or rude language	minumura mura ako teh	Pending	2025-10-12 05:21:28.159017+08	3	5	5
6	Trade Issues	Misleading description	iba naman yung talagang trade namin	Pending	2025-10-12 05:37:11.245279+08	3	5	5
\.


--
-- Data for Name: repsys_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.repsys_tbl (repsys_id, tradereq_id, requester_starcount, responder_starcount, requester_rating_desc, responder_rating_desc, requester_rated_at, responder_rated_at) FROM stdin;
\.


--
-- Data for Name: specskills_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.specskills_tbl (specskills_id, genskills_id, speccateg) FROM stdin;
1	1	Graphic Design
2	1	Photography
3	1	Video Editing
4	1	Illustration
5	1	Animation
6	2	Web Development
7	2	Software Development
8	2	IT Support
9	2	Network Administration
10	2	Cybersecurity
11	3	Project Management
12	3	Business Consulting
13	3	Human Resources
14	3	Operations Management
15	3	Marketing Strategy
16	4	Customer Service
17	4	Public Relations
18	4	Copywriting
21	5	Nutrition Coaching
22	5	Personal Training
23	5	Mental Health Counseling
24	5	Yoga Instruction
26	6	Tutoring
27	6	Language Instruction
28	6	Corporate Training
29	6	Curriculum Development
30	6	Test Preparation
31	7	Interior Decorating
32	7	Cleaning Services
33	7	Gardening
34	7	Event Planning
35	7	Personal Assistance
36	8	Furniture Assembly
37	8	Sewing & Alterations
38	8	Handyman Services
39	8	Painting & Decorating
40	8	Crafting
41	9	Social Media Management
42	9	Content Creation
43	9	SEO
44	9	Digital Advertising
45	9	Email Marketing
46	10	Translation
47	10	Interpretation
48	10	Language Tutoring
49	10	Transcription
50	10	Localization
51	11	Bookkeeping
52	11	Tax Preparation
53	11	Financial Planning
54	11	Payroll Services
55	11	Auditing
56	12	Personal Training
57	12	Group Fitness Instruction
58	12	Sports Coaching
59	12	Nutrition for Athletes
60	12	Physical Therapy
61	13	Music Lessons
62	13	Dance Instruction
63	13	Acting Coaching
64	13	Visual Arts
65	13	Creative Writing
66	14	Diversity Training
67	14	Cultural Consulting
68	14	Language & Cultural Exchange
69	14	Community Outreach
70	14	Inclusion Workshops
71	15	Market Research
72	15	Data Analysis
73	15	Academic Research
74	15	Competitive Analysis
75	15	Strategic Planning
19	4	Multilingual Communication
20	4	Online Community Engagement
25	5	Fitness Coaching
\.


--
-- Data for Name: supptix_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.supptix_tbl (ticket_id, user_id, ticket_name, ticket_email, ticket_title, ticket_desc, ticket_pic, ticket_datesubmitted) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2025-10-08 03:57:28.375407+08	1
2	2025-10-08 05:27:52.817447+08	2
3	2025-10-08 05:59:32.127723+08	3
4	2025-10-08 06:07:01.373512+08	4
5	2025-10-09 23:42:37.162745+08	5
6	2025-10-09 23:51:06.561459+08	8
7	2025-10-10 00:18:25.138408+08	9
8	2025-10-10 00:21:45.767337+08	10
9	2025-10-10 00:33:25.420968+08	11
10	2025-10-10 00:40:14.683838+08	12
11	2025-10-10 01:31:44.699997+08	14
12	2025-10-10 02:02:55.651157+08	13
13	2025-10-10 02:02:59.847+08	15
14	2025-10-10 02:08:41.608781+08	16
15	2025-10-10 03:56:14.024613+08	17
16	2025-10-10 04:00:48.394023+08	19
17	2025-10-10 04:01:37.707251+08	22
18	2025-10-10 04:11:50.909762+08	18
19	2025-10-10 04:53:04.136944+08	23
20	2025-10-11 07:29:01.959242+08	26
21	2025-10-11 07:29:31.243227+08	25
22	2025-10-11 07:31:24.451323+08	30
23	2025-10-11 23:10:46.642919+08	32
24	2025-10-12 02:46:49.663469+08	34
25	2025-10-12 02:47:07.133972+08	35
26	2025-10-12 02:47:52.771813+08	36
27	2025-10-12 03:11:11.367868+08	37
28	2025-10-12 03:12:30.199054+08	38
29	2025-10-12 03:17:50.378719+08	39
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ3MDY2MywiaWF0IjoxNzU5ODY1ODYzLCJqdGkiOiI1OGU5ZDVlZjYwYmY0NTA2ODIwMmQ2YjIwZGQyMTgyNSIsInVzZXJfaWQiOiIxIn0.1201g4ah0BU3ykCGT5Wq4zIO1erA2lgyEiUlDGpv0Pc	2025-10-08 03:37:43.940172+08	2025-10-15 03:37:43+08	1	58e9d5ef60bf45068202d6b20dd21825
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ3MzYzOCwiaWF0IjoxNzU5ODY4ODM4LCJqdGkiOiI0NDYyOGM4OWMyYTQ0ZTBiOWViNDJiYTIyYjcxNDU2NiIsInVzZXJfaWQiOiIyIn0.xKJXXEUcWrCVsInVFwmzen0qgd2mzxm9hkgn3FTYpf4	2025-10-08 04:27:18.036062+08	2025-10-15 04:27:18+08	2	44628c89c2a44e0b9eb42ba22b714566
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ3NzI5MCwiaWF0IjoxNzU5ODcyNDkwLCJqdGkiOiJmNWI1MTYwMDEyMzU0NTAzODA1MTVkOTdhNDEyN2U3MyIsInVzZXJfaWQiOiIyIn0.-3wpuDr4VkmNXodbLwT_B8GK1HtN-5XEZqTJsNXcs7U	2025-10-08 05:28:10.292246+08	2025-10-15 05:28:10+08	2	f5b516001235450380515d97a4127e73
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ3OTUxNCwiaWF0IjoxNzU5ODc0NzE0LCJqdGkiOiI0NTA1MTExYmU2YzM0YzcyYjA1ODUyODQyOGRiNjBhMSIsInVzZXJfaWQiOiIzIn0.RzSlJXCfXMaenB2OrggephvPXM16qsjEdSyVtmFz6GE	2025-10-08 06:05:14.281545+08	2025-10-15 06:05:14+08	3	4505111be6c34c72b058528428db60a1
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ3OTYzNywiaWF0IjoxNzU5ODc0ODM3LCJqdGkiOiIwMjY1M2ViYTFlMDY0MjlmOGYwNzUxOGFlMTJlYjkyOSIsInVzZXJfaWQiOiIzIn0.xTuER9OEuiYkE5CGf455_9OSOhadQtYXLs0yL1lES-I	2025-10-08 06:07:17.184438+08	2025-10-15 06:07:17+08	3	02653eba1e06429f8f07518ae12eb929
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ4MDM1NiwiaWF0IjoxNzU5ODc1NTU2LCJqdGkiOiI5MzM1NTViZDRmNTU0MWQ0YTQ0NDc4ZDgzNzI5YTdhMyIsInVzZXJfaWQiOiIyIn0.bp5gZB3a-HSoC-TCNvvr34O2R8yoJ_GfUstTsvwZrAY	2025-10-08 06:19:16.144211+08	2025-10-15 06:19:16+08	2	933555bd4f5541d4a44478d83729a7a3
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYyOTM1NCwiaWF0IjoxNzYwMDI0NTU0LCJqdGkiOiI2MDhkMTExYTFkOTc0ZjJiYjQwMjkwYWIwMWNiNmY0NCIsInVzZXJfaWQiOiIzIn0.x0shQlTa60FAdt48ba99x48V0qqvMTbVrbOhQ9dSF18	2025-10-09 23:42:34.94326+08	2025-10-16 23:42:34+08	3	608d111a1d974f2bb40290ab01cb6f44
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYyOTQwMywiaWF0IjoxNzYwMDI0NjAzLCJqdGkiOiJkNjgxYTY0MzFhNjk0NjM4OWZiNGQ1YWY3OTM4M2NkOSIsInVzZXJfaWQiOiIxIn0.9_VGv56yI-n_ejT9O2BPa62vh5Vrg3YCqPbOFQv3Z3U	2025-10-09 23:43:23.919987+08	2025-10-16 23:43:23+08	1	d681a6431a6946389fb4d5af79383cd9
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYyOTk0OSwiaWF0IjoxNzYwMDI1MTQ5LCJqdGkiOiI5M2YwZTNkYTE2OGY0OGRiYjRjYTNmNjNlMDYwOWFjNiIsInVzZXJfaWQiOiI0In0.Bvh_UruZO_sHru1KzkVCLsDXa8dlwbETkbDEuE8v_mc	2025-10-09 23:52:29.078829+08	2025-10-16 23:52:29+08	4	93f0e3da168f48dbb4ca3f63e0609ac6
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzMTU0OCwiaWF0IjoxNzYwMDI2NzQ4LCJqdGkiOiIxZmM3NWMyZTQ4ZjI0MGM5YjY3YzhlZjM3ZWExYTcyZSIsInVzZXJfaWQiOiI0In0.jB6aoUG8zBmhI5c0GJH24BnXeMekjZ-kD0LyEMRJeJw	2025-10-10 00:19:08.744079+08	2025-10-17 00:19:08+08	4	1fc75c2e48f240c9b67c8ef37ea1a72e
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzMTcyMywiaWF0IjoxNzYwMDI2OTIzLCJqdGkiOiI0YTRkMjA3YWY3ZDI0ODAxODJhNmQ4NTI5YTgwZDExZCIsInVzZXJfaWQiOiI0In0.k3J4KRC0b-ZZoAgSpRz81gV4uC9ZvPClD9Uvb4jwTkY	2025-10-10 00:22:03.714644+08	2025-10-17 00:22:03+08	4	4a4d207af7d2480182a6d8529a80d11d
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzMjQyOCwiaWF0IjoxNzYwMDI3NjI4LCJqdGkiOiJiNDIxNmVkMGIzNGE0ODBlYWY4ZDM1NDRjZmQ5NDg4ZCIsInVzZXJfaWQiOiI0In0.0F2sCJ0ywYM9Uv_iVbniq4kR79z0nRVCvxWW0GVlmNE	2025-10-10 00:33:48.950082+08	2025-10-17 00:33:48+08	4	b4216ed0b34a480eaf8d3544cfd9488d
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzMzYyMiwiaWF0IjoxNzYwMDI4ODIyLCJqdGkiOiJiYjExNjI3NWU4ZGY0OTAwOGM3MTUyN2QwMDllZmZmNSIsInVzZXJfaWQiOiI0In0.ktT9lQ73sDR6i8Zq2q-JKKRJ03r1Fn_Us0v1Ma3NNgw	2025-10-10 00:53:42.130858+08	2025-10-17 00:53:42+08	4	bb116275e8df49008c71527d009efff5
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzNTg3NSwiaWF0IjoxNzYwMDMxMDc1LCJqdGkiOiJhNTUyODAzM2UwZjQ0MzI3ODVmZmVjYmE3ZDVkMWE1OSIsInVzZXJfaWQiOiIzIn0.RW_aizWyBDvIqjxZu53x8FAy4QDKFM1sqx8AjJCpxYo	2025-10-10 01:31:15.898322+08	2025-10-17 01:31:15+08	3	a5528033e0f4432785ffecba7d5d1a59
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzNTkxOCwiaWF0IjoxNzYwMDMxMTE4LCJqdGkiOiIxMDRiMmEzZDcwYjE0MjVhODI5NTRlOGNjNTk0ZmU5NCIsInVzZXJfaWQiOiIyIn0.mZDKg9N4ALWkQlFErkdIWrk4daCq2FA-yqIOt_2R1MU	2025-10-10 01:31:58.713638+08	2025-10-17 01:31:58+08	2	104b2a3d70b1425a82954e8cc594fe94
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzNzc5OCwiaWF0IjoxNzYwMDMyOTk4LCJqdGkiOiI1M2Q1ODZkZWI5ZjM0MzE4ODQxNGIyMDJjYzAzYmZlMyIsInVzZXJfaWQiOiIxIn0.RHNPY-OugbaWhKYTFiCromxmA8hHtTn6ARC-VOWaT-g	2025-10-10 02:03:18.552341+08	2025-10-17 02:03:18+08	1	53d586deb9f343188414b202cc03bfe3
17	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzNzgxMywiaWF0IjoxNzYwMDMzMDEzLCJqdGkiOiI0YTE5M2I2NThkMTU0MGY3OTkwODI2ZjRlMzMzMTNiYiIsInVzZXJfaWQiOiI0In0.NwMxGBIvBwWngHpGLIq2HUj2ytajysbkDYyP7C-kuRI	2025-10-10 02:03:33.439577+08	2025-10-17 02:03:33+08	4	4a193b658d1540f7990826f4e33313bb
18	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzNzk4NCwiaWF0IjoxNzYwMDMzMTg0LCJqdGkiOiI1ZGUyYTkxNjNkMzg0MmVkYmQwM2NkMTk0YWE0MDliMCIsInVzZXJfaWQiOiIzIn0.w3Z0kdXrbHF6OV-7wE6rZV2R062VsiYBIi25T3ERl7E	2025-10-10 02:06:24.61896+08	2025-10-17 02:06:24+08	3	5de2a9163d3842edbd03cd194aa409b0
19	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDYzODE0MSwiaWF0IjoxNzYwMDMzMzQxLCJqdGkiOiIzNjllZGFjOGMwZjI0YzJjOTIyZWRhMzlhNWU4NjBhYSIsInVzZXJfaWQiOiIyIn0.EHvMRZonKC0cGOyXcFyMW9YuRYuKOOFnwqRrpN62fis	2025-10-10 02:09:01.728348+08	2025-10-17 02:09:01+08	2	369edac8c0f24c2c922eda39a5e860aa
20	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDY0NDU3MSwiaWF0IjoxNzYwMDM5NzcxLCJqdGkiOiIyMzE5MTY0OTdmMjI0OTY3YTUyNDRiZDBmN2UyYzM4OSIsInVzZXJfaWQiOiI0In0.hr9KkI4LhuxtxE6kFXRBey18I717HlE5djjEV5xrEzY	2025-10-10 03:56:11.911385+08	2025-10-17 03:56:11+08	4	231916497f224967a5244bd0f7e2c389
21	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDY0NDg0NSwiaWF0IjoxNzYwMDQwMDQ1LCJqdGkiOiIyMzBiNDBhZTdlZWQ0OWVkOTEyOThkOWFlMWQ2ZDUxZSIsInVzZXJfaWQiOiIyIn0.71gIaQwHkkqC6fbnGBDZlWG4oOdXoUj25ea__ZxHrxc	2025-10-10 04:00:45.602904+08	2025-10-17 04:00:45+08	2	230b40ae7eed49ed91298d9ae1d6d51e
22	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDY0NDg4MCwiaWF0IjoxNzYwMDQwMDgwLCJqdGkiOiJhNjE3ZmNkMjVmMDg0MzIwYmMzM2MwMDk1Njc5ZWQ2MCIsInVzZXJfaWQiOiIxIn0.emhoGOCXPRLoQn-klchcAiRSvQB5nPqit0tb1O-Yp2I	2025-10-10 04:01:20.496983+08	2025-10-17 04:01:20+08	1	a617fcd25f084320bc33c0095679ed60
23	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDY0NDk3NCwiaWF0IjoxNzYwMDQwMTc0LCJqdGkiOiIwM2RlZDc3OThiMDI0MDA4YTMwMzJhNjQ4ZTQ2YjUwZiIsInVzZXJfaWQiOiIyIn0.K5UYwo-T6JTZhK7YMu8hR9ot8OjEO1ZVpwl7kj5k9jo	2025-10-10 04:02:54.539173+08	2025-10-17 04:02:54+08	2	03ded7798b024008a3032a648e46b50f
24	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDY0NTUwOCwiaWF0IjoxNzYwMDQwNzA4LCJqdGkiOiI4MDgxZTVjODQwMzM0NmJlOTMxMmQ5ZjJjN2Q3OTg2MCIsInVzZXJfaWQiOiIzIn0.O9BTeZLcE_00zXxXHjvXlJR9v6xFVoJmT1r3ZGOdYOw	2025-10-10 04:11:48.347554+08	2025-10-17 04:11:48+08	3	8081e5c8403346be9312d9f2c7d79860
25	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDczNzA3OSwiaWF0IjoxNzYwMTMyMjc5LCJqdGkiOiIyOWMxYzU5MTc3YjU0MTM2YWY1YjQyNjViYmY3NjAyOCIsInVzZXJfaWQiOiIzIn0.c7qUAgduTFIpOhhJ1NZfY-4d_VZmk7EIsNHcj3rjoNY	2025-10-11 05:37:59.751083+08	2025-10-18 05:37:59+08	3	29c1c59177b54136af5b4265bbf76028
26	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDczNzA4NSwiaWF0IjoxNzYwMTMyMjg1LCJqdGkiOiI3ZjhiN2MyNjVlMzE0MjY3OTQ1MDI4Yjk0MjU0MmEyMiIsInVzZXJfaWQiOiIyIn0.Z8Sa4KriD7MrN2lnG_QCv2oa4MXrclBQMw-vLYKlCmU	2025-10-11 05:38:05.26663+08	2025-10-18 05:38:05+08	2	7f8b7c265e314267945028b942542a22
27	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDc0MzczOSwiaWF0IjoxNzYwMTM4OTM5LCJqdGkiOiI2NjAzNjJjMDM3ZmU0MTY4OGFiMzY5NWU1NjA2MzMwOSIsInVzZXJfaWQiOiIyIn0.Z_3NhX0FRgJQy3W1tfebQ4fUztLhvoYYIUNK4oCHiV8	2025-10-11 07:28:59.479234+08	2025-10-18 07:28:59+08	2	660362c037fe41688ab3695e56063309
28	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDc0Mzc2OCwiaWF0IjoxNzYwMTM4OTY4LCJqdGkiOiIyODEzN2U5YTA0YzQ0NWFjOWJiODU2NjdiMWM3MzU5ZiIsInVzZXJfaWQiOiIzIn0.R1L20TM7jjdRkz3TAuOz44T09SFQAITaEO6dI7nF404	2025-10-11 07:29:28.974497+08	2025-10-18 07:29:28+08	3	28137e9a04c445ac9bb85667b1c7359f
29	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDc0MzgwOSwiaWF0IjoxNzYwMTM5MDA5LCJqdGkiOiIxNzJkNGY3NmZlYmI0YTRkODYwOGRiYzg3NjNiMDU5ZCIsInVzZXJfaWQiOiIzIn0.KV6C4M_B7wTB6BRqrrKNDaBG_MwMBBo1SUbSGBv-lMw	2025-10-11 07:30:09.714577+08	2025-10-18 07:30:09+08	3	172d4f76febb4a4d8608dbc8763b059d
30	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDc0Mzg3MiwiaWF0IjoxNzYwMTM5MDcyLCJqdGkiOiI3MDk1NjkzMTE0ZjY0YTdiYTk5YWUwNzgwZjI0MWU5MSIsInVzZXJfaWQiOiIxIn0.6vksnk_vwhJnKLA4W8SdyJtNCfeuPig-G_50tRW4R2E	2025-10-11 07:31:12.943567+08	2025-10-18 07:31:12+08	1	7095693114f64a7ba99ae0780f241e91
31	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDc0Mzg5OCwiaWF0IjoxNzYwMTM5MDk4LCJqdGkiOiJmZTVjZDFhODBkNTM0ZjY2YjYwMDA3ZTM4MzIzNDhhOCIsInVzZXJfaWQiOiIyIn0.VU1sU7YnmijZgASOtfQjCFTo06GCNV6W5aA8qd3qD-w	2025-10-11 07:31:38.492847+08	2025-10-18 07:31:38+08	2	fe5cd1a80d534f66b60007e3832348a8
32	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDc0NTg3NiwiaWF0IjoxNzYwMTQxMDc2LCJqdGkiOiJkNGQyMDY3NTQyMTE0NzA5ODk3MGRhMDgyYmExZDVlMSIsInVzZXJfaWQiOiI0In0.L2o9-r_d2g1LbQmTt_ZAqoq-jZNa5YktWyWgqbe5eOg	2025-10-11 23:10:46.272016+08	2025-10-18 08:04:36+08	4	d4d20675421147098970da082ba1d5e1
33	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgwMDI0NiwiaWF0IjoxNzYwMTk1NDQ2LCJqdGkiOiIyNjc2ZmQ3NWQwMmI0ZjQ4YWI4NjZiYTg1MTQ2ODQzYyIsInVzZXJfaWQiOiI0In0.f1lFyDKy5hZQ7sP7kgz7MpES-TH8Hrnisq8x4_wYrnk	2025-10-11 23:10:46.272016+08	2025-10-18 23:10:46+08	4	2676fd75d02b4f48ab866ba85146843c
34	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxMjc1OSwiaWF0IjoxNzYwMjA3OTU5LCJqdGkiOiI0ZWMzYzY1YTQ0MmE0ZTAyODQ2ZDNjYjU2ZWRlOTIxZSIsInVzZXJfaWQiOiI1In0.YYu2GOGlUhk0CzhtcNu9eTtQB0mNJfqgQsY5jNI-uuE	2025-10-12 02:39:19.377624+08	2025-10-19 02:39:19+08	5	4ec3c65a442a4e02846d3cb56ede921e
35	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxMzIyMywiaWF0IjoxNzYwMjA4NDIzLCJqdGkiOiJlZDM3MWNkZDY5N2U0ODdkOTc4YzdjNWMxOGE3MjNhYiIsInVzZXJfaWQiOiI1In0.sLrQv5HPsJIqV51N1aU5Z3dkVKD_Ke13wfBn2md32o4	2025-10-12 02:47:03.26428+08	2025-10-19 02:47:03+08	5	ed371cdd697e487d978c7c5c18a723ab
36	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxMzIzMywiaWF0IjoxNzYwMjA4NDMzLCJqdGkiOiI0ZDM2OTc4NWY0YWM0NmYxOGMxYWI3M2M2MjNlNzQ5OSIsInVzZXJfaWQiOiIyIn0.MLRyLF3LUGU3eCXwtmXdADACCd1cVQJj9Bo-rFP0l1c	2025-10-12 02:47:13.884393+08	2025-10-19 02:47:13+08	2	4d369785f4ac46f18c1ab73c623e7499
37	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxMzI3OSwiaWF0IjoxNzYwMjA4NDc5LCJqdGkiOiI5NTMyYmI3ZWQ1M2M0ODMxODgxODY0MjNkNzk4NTgxMSIsInVzZXJfaWQiOiI1In0.ciY_55o5Q60kwtguf_0939tgp79IKpPVsejFSfVPSXE	2025-10-12 02:47:59.86486+08	2025-10-19 02:47:59+08	5	9532bb7ed53c483188186423d7985811
38	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxNDcxNiwiaWF0IjoxNzYwMjA5OTE2LCJqdGkiOiIzNTdhMWJhN2ZlMTg0YTc1ODVmMTllMjljOWE2ZGNjZSIsInVzZXJfaWQiOiIzIn0.0-Ld08M-Qdct44WZQ4B6fZfjSaAdHLDT0bzxxHuik3M	2025-10-12 03:11:56.825+08	2025-10-19 03:11:56+08	3	357a1ba7fe184a7585f19e29c9a6dcce
39	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxNDc2NywiaWF0IjoxNzYwMjA5OTY3LCJqdGkiOiJhMWZkOWIxMjI1OWI0ZWUzYjk1ODA1ODMyMWJiNmU2NSIsInVzZXJfaWQiOiIyIn0.eoMV-8GJaiVhCfnlOvXLTmq9F6dkjnNvxBG2DKFbNiw	2025-10-12 03:12:47.218685+08	2025-10-19 03:12:47+08	2	a1fd9b12259b4ee3b958058321bb6e65
40	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgxNTgzMSwiaWF0IjoxNzYwMjExMDMxLCJqdGkiOiIwMjNhODFmZDc1NTk0N2UyYTI0ZmFmYmU0N2Y1ZDVmMiIsInVzZXJfaWQiOiI1In0.D-NmfVdv2SPKWoQ_y5IWPBHA7scPG4CJNiKGMxmvsV0	2025-10-12 03:30:31.070195+08	2025-10-19 03:30:31+08	5	023a81fd755947e2a24fafbe47f5d5f2
41	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDgyMzQxNywiaWF0IjoxNzYwMjE4NjE3LCJqdGkiOiIyNGNjMWI5ZDA4YzQ0ZGJhYTM3NjI1MDc4ZDA0ZTg3OSIsInVzZXJfaWQiOiI1In0.rBGKqtmIQxPm3ns6eTtXcwQBn_yzgzVq8JgL1XLLM9s	2025-10-12 05:36:57.913958+08	2025-10-19 05:36:57+08	5	24cc1b9d08c44dbaa37625078d04e879
\.


--
-- Data for Name: trade_details_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trade_details_tbl (tradedetails_id, tradereq_id, user_id, skillprof, modedel, reqtype, contextpic, reqbio, created_at, total_xp) FROM stdin;
\.


--
-- Data for Name: trade_interests_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trade_interests_tbl (trade_interests_id, tradereq_id, interested_user_id, created_at, status) FROM stdin;
1	1	2	2025-10-11 06:06:18.677319+08	PENDING
3	4	2	2025-10-12 02:47:47.669864+08	ACCEPTED
\.


--
-- Data for Name: tradehis_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tradehis_tbl (tradehis_id, tradereq_id, completed_at, requester_proof, responder_proof, requester_proof_status, responder_proof_status) FROM stdin;
\.


--
-- Data for Name: tradereq_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tradereq_tbl (tradereq_id, requester_id, responder_id, reqname, reqdeadline, status, exchangename, classifiedcategory, created_at, requester_rated, responder_rated) FROM stdin;
1	3	\N	Dishwasher	2025-11-07	\N	\N	\N	2025-10-10 22:05:56.24863	f	f
2	2	\N	Plumbing	2025-11-08	\N	\N	\N	2025-10-10 22:23:17.280954	f	f
4	5	2	Fitness Trainer	2025-11-08	PENDING	Business & Management	\N	2025-10-11 18:39:26.821118	f	f
5	3	\N	IT Support	2025-11-05	\N	\N	\N	2025-10-11 19:12:18.77951	f	f
\.


--
-- Data for Name: usercredentials_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usercredentials_tbl (usercred_id, user_id, credential_title, issuer, issue_date, expiry_date, cred_id, cred_url, genskills_id, specskills_id, created_at) FROM stdin;
\.


--
-- Data for Name: userinterests_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.userinterests_tbl (userinterests_id, user_id, genskills_id) FROM stdin;
1	1	7
2	1	8
3	1	9
4	2	3
5	2	8
6	3	11
7	3	12
8	4	1
9	4	6
10	4	11
11	5	2
12	5	1
\.


--
-- Data for Name: users_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_tbl (user_id, first_name, last_name, username, email, password, profilepic, bio, location, ratingcount, avgstars, tot_xppts, created_at, userverifyid, links, level, is_verified, verification_status, is_active) FROM stdin;
2	Elli	Cecilia	ellidp	xxlianna.dp@gmail.com	pbkdf2_sha256$600000$U84t4Cgcrm2cPySkHImBmJ$E99b6KHmT1Z1l3csUypTUUBZD5YCFhVgKFfEUUREuok=	https://res.cloudinary.com/dyj3ojsip/image/upload/v1759872574/media/profile_pics/cqsr1ineipi6tcmwaapq.jpg	tryyyyyyyyyy	Arayat Street Parang, Marikina, Philippines	0	0.00	0	2025-10-07 20:27:08.944371	https://res.cloudinary.com/dyj3ojsip/raw/upload/v1759868833/media/user_verifications/user_2_verification.pdf	[]	1	f	PENDING	t
4	Nehemiah	Dizon	nehemdiz	nehemiahdizon@gmail.com	pbkdf2_sha256$600000$wLMI0yQ4cthl5QKviZQUvU$zFL1afzwAjkGdBM0b+GSZK83rqsqub2u5KDjJJouCbI=	https://res.cloudinary.com/dyj3ojsip/image/upload/v1760027663/media/profile_pics/tbhxya0q0lwjsmjz5k1u.jpg	mhhhhhhhhmmmmm	Daisy Street Santo Niño, San Mateo, Rizal, Philippines	0	0.00	0	2025-10-09 15:52:26.007889	\N	[]	1	f	UNVERIFIED	t
1	Ellianna	Cecilia Principe	elliannadp	elliannaprincipe06@gmail.com	pbkdf2_sha256$600000$QUqMCaYItHHntc0Uo3A0Qo$dRuGvWEAL0XaOUhhQfkFW73F8obZxNliahXq1W9KPXs=	https://res.cloudinary.com/dyj3ojsip/image/upload/v1760033102/media/profile_pics/br24ucctpeh4fudfrlmr.jpg	hmmmmmmmmmmmmmmm yessssss	Dollar Street Rosario, Rodriguez, Rizal, Philippines	0	0.00	0	2025-10-07 19:37:40.229754	Principe_3Y2S - COR.pdf	["https://instagram.com/ellianna.dp", "https://facebook.com/elliannacecilia"]	1	f	PENDING	t
3	Francis	Chuaunsu	fjaeeee	chuaunsufrancis@gmail.com	pbkdf2_sha256$600000$FoVv9Pg5Hyy6Euf6lTE43h$XbEmOjxk8JcCfLX6Umh+fvTQ8w5Wz//izSf69LCR4BI=	https://res.cloudinary.com/dyj3ojsip/image/upload/v1760033272/media/profile_pics/n7rzykeyimb29tzxqry1.jpg	ihhhhhhhhhhhhh	Oxford Drive Nangka, Marikina, Philippines	0	0.00	0	2025-10-07 22:05:11.120109	\N	[]	1	f	UNVERIFIED	t
5	Nehemiah Andrew	Dizon	miahdznie	nehem.dizon@gmail.com	pbkdf2_sha256$600000$NW0itYUh8U76UC2ky3ybiQ$4MfWeDZ5poLNmGMoSlKIw6vvmBYiyOUEAGIhjmm47gE=	https://res.cloudinary.com/dyj3ojsip/image/upload/v1760207956/media/profile_pics/user_5_profile.png	meow meow meow meowww	Hinahon Street Barangka Ibaba, Mandaluyong, Philippines	0	0.00	0	2025-10-11 18:39:15.028026	https://res.cloudinary.com/dyj3ojsip/image/upload/v1760207958/media/user_verifications/user_5_verification.jpg	["instagram.com/mandnemz"]	1	f	PENDING	t
\.


--
-- Data for Name: userskills_tbl; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.userskills_tbl (userskills_id, user_id, specskills_id, created_at) FROM stdin;
1	1	34	2025-10-08 03:37:41.086231+08
2	1	35	2025-10-08 03:37:41.095916+08
3	1	38	2025-10-08 03:37:41.098869+08
4	1	36	2025-10-08 03:37:41.101694+08
5	1	43	2025-10-08 03:37:41.107397+08
6	1	41	2025-10-08 03:37:41.110709+08
7	2	13	2025-10-08 04:27:14.132484+08
8	2	36	2025-10-08 04:27:14.139645+08
9	3	54	2025-10-08 06:05:11.21587+08
10	3	52	2025-10-08 06:05:11.219552+08
11	3	60	2025-10-08 06:05:11.222736+08
12	3	59	2025-10-08 06:05:11.22956+08
13	3	56	2025-10-08 06:05:11.232337+08
14	4	1	2025-10-09 23:52:26.245378+08
15	4	4	2025-10-09 23:52:26.249101+08
16	4	2	2025-10-09 23:52:26.254543+08
17	4	27	2025-10-09 23:52:26.258647+08
18	4	30	2025-10-09 23:52:26.26196+08
19	4	26	2025-10-09 23:52:26.267731+08
20	4	53	2025-10-09 23:52:26.270347+08
21	4	51	2025-10-09 23:52:26.272927+08
22	5	1	2025-10-12 02:39:18.904813+08
23	5	4	2025-10-12 02:39:18.909822+08
24	5	8	2025-10-12 02:39:18.91252+08
25	5	10	2025-10-12 02:39:18.913525+08
26	5	9	2025-10-12 02:39:18.916533+08
27	5	7	2025-10-12 02:39:18.918533+08
28	5	6	2025-10-12 02:39:18.920529+08
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 96, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: conversations_tbl_conversation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.conversations_tbl_conversation_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 24, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 65, true);


--
-- Name: evaluation_tbl_evaluation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluation_tbl_evaluation_id_seq', 1, false);


--
-- Name: genskills_tbl_genskills_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.genskills_tbl_genskills_id_seq', 15, true);


--
-- Name: messages_tbl_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_tbl_message_id_seq', 1, true);


--
-- Name: password_reset_token_tbl_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_token_tbl_id_seq', 1, false);


--
-- Name: reports_tbl_report_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reports_tbl_report_id_seq', 6, true);


--
-- Name: repsys_tbl_repsys_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.repsys_tbl_repsys_id_seq', 1, false);


--
-- Name: specskills_tbl_specskills_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.specskills_tbl_specskills_id_seq', 75, true);


--
-- Name: supptix_tbl_ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supptix_tbl_ticket_id_seq', 1, false);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 29, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 41, true);


--
-- Name: trade_details_tbl_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trade_details_tbl_id_seq', 1, false);


--
-- Name: trade_interests_tbl_trade_interests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trade_interests_tbl_trade_interests_id_seq', 3, true);


--
-- Name: tradehis_tbl_tradehis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tradehis_tbl_tradehis_id_seq', 1, false);


--
-- Name: tradereq_tbl_tradereq_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tradereq_tbl_tradereq_id_seq', 5, true);


--
-- Name: usercerts_tbl_cert_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usercerts_tbl_cert_id_seq', 1, false);


--
-- Name: userinterests_tbl_usergeninterests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.userinterests_tbl_usergeninterests_id_seq', 12, true);


--
-- Name: users_tbl_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_tbl_user_id_seq', 5, true);


--
-- Name: userskills_tbl_userskills_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.userskills_tbl_userskills_id_seq', 28, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: conversations_tbl conversations_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations_tbl
    ADD CONSTRAINT conversations_tbl_pkey PRIMARY KEY (conversation_id);


--
-- Name: conversations_tbl conversations_tbl_tradereq_id_b2e37107_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations_tbl
    ADD CONSTRAINT conversations_tbl_tradereq_id_b2e37107_uniq UNIQUE (tradereq_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: evaluation_tbl evaluation_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_tbl
    ADD CONSTRAINT evaluation_tbl_pkey PRIMARY KEY (evaluation_id);


--
-- Name: genskills_tbl genskills_tbl_gencateg_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genskills_tbl
    ADD CONSTRAINT genskills_tbl_gencateg_key UNIQUE (gencateg);


--
-- Name: genskills_tbl genskills_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genskills_tbl
    ADD CONSTRAINT genskills_tbl_pkey PRIMARY KEY (genskills_id);


--
-- Name: messages_tbl messages_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages_tbl
    ADD CONSTRAINT messages_tbl_pkey PRIMARY KEY (message_id);


--
-- Name: password_reset_token_tbl password_reset_token_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token_tbl
    ADD CONSTRAINT password_reset_token_tbl_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token_tbl password_reset_token_tbl_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token_tbl
    ADD CONSTRAINT password_reset_token_tbl_token_key UNIQUE (token);


--
-- Name: reports_tbl reports_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_tbl
    ADD CONSTRAINT reports_tbl_pkey PRIMARY KEY (report_id);


--
-- Name: repsys_tbl repsys_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repsys_tbl
    ADD CONSTRAINT repsys_tbl_pkey PRIMARY KEY (repsys_id);


--
-- Name: specskills_tbl specskills_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specskills_tbl
    ADD CONSTRAINT specskills_tbl_pkey PRIMARY KEY (specskills_id);


--
-- Name: supptix_tbl supptix_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supptix_tbl
    ADD CONSTRAINT supptix_tbl_pkey PRIMARY KEY (ticket_id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: trade_details_tbl trade_details_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_details_tbl
    ADD CONSTRAINT trade_details_tbl_pkey PRIMARY KEY (tradedetails_id);


--
-- Name: trade_interests_tbl trade_interests_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_interests_tbl
    ADD CONSTRAINT trade_interests_tbl_pkey PRIMARY KEY (trade_interests_id);


--
-- Name: tradehis_tbl tradehis_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradehis_tbl
    ADD CONSTRAINT tradehis_tbl_pkey PRIMARY KEY (tradehis_id);


--
-- Name: tradereq_tbl tradereq_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradereq_tbl
    ADD CONSTRAINT tradereq_tbl_pkey PRIMARY KEY (tradereq_id);


--
-- Name: specskills_tbl unique_genskill_speccateg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specskills_tbl
    ADD CONSTRAINT unique_genskill_speccateg UNIQUE (genskills_id, speccateg);


--
-- Name: trade_details_tbl unique_trade_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_details_tbl
    ADD CONSTRAINT unique_trade_user UNIQUE (tradereq_id, user_id);


--
-- Name: trade_interests_tbl unique_trade_user_interest; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_interests_tbl
    ADD CONSTRAINT unique_trade_user_interest UNIQUE (tradereq_id, interested_user_id);


--
-- Name: CONSTRAINT unique_trade_user_interest ON trade_interests_tbl; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON CONSTRAINT unique_trade_user_interest ON public.trade_interests_tbl IS 'Prevents same user from expressing interest twice in same trade';


--
-- Name: userskills_tbl uq_user_spec; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl
    ADD CONSTRAINT uq_user_spec UNIQUE (user_id, specskills_id);


--
-- Name: usercredentials_tbl usercerts_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usercredentials_tbl
    ADD CONSTRAINT usercerts_tbl_pkey PRIMARY KEY (usercred_id);


--
-- Name: userinterests_tbl userinterests_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterests_tbl
    ADD CONSTRAINT userinterests_tbl_pkey PRIMARY KEY (userinterests_id);


--
-- Name: userinterests_tbl userinterests_tbl_user_id_genskills_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterests_tbl
    ADD CONSTRAINT userinterests_tbl_user_id_genskills_id_key UNIQUE (user_id, genskills_id);


--
-- Name: users_tbl users_tbl_emailadd_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tbl
    ADD CONSTRAINT users_tbl_emailadd_key UNIQUE (email);


--
-- Name: users_tbl users_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tbl
    ADD CONSTRAINT users_tbl_pkey PRIMARY KEY (user_id);


--
-- Name: users_tbl users_tbl_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_tbl
    ADD CONSTRAINT users_tbl_username_key UNIQUE (username);


--
-- Name: userskills_tbl userskills_tbl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl
    ADD CONSTRAINT userskills_tbl_pkey PRIMARY KEY (userskills_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: conversations_tbl_requester_id_7b9c70b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX conversations_tbl_requester_id_7b9c70b6 ON public.conversations_tbl USING btree (requester_id);


--
-- Name: conversations_tbl_responder_id_4d0fae4d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX conversations_tbl_responder_id_4d0fae4d ON public.conversations_tbl USING btree (responder_id);


--
-- Name: conversations_tbl_tradereq_id_b2e37107; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX conversations_tbl_tradereq_id_b2e37107 ON public.conversations_tbl USING btree (tradereq_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_evaluation_tradereq_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_evaluation_tradereq_id ON public.evaluation_tbl USING btree (tradereq_id);


--
-- Name: idx_trade_interests_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trade_interests_created_at ON public.trade_interests_tbl USING btree (created_at DESC);


--
-- Name: idx_trade_interests_trade_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trade_interests_trade_status ON public.trade_interests_tbl USING btree (tradereq_id, status);


--
-- Name: idx_trade_interests_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trade_interests_user ON public.trade_interests_tbl USING btree (interested_user_id);


--
-- Name: idx_userskills_spec; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_userskills_spec ON public.userskills_tbl USING btree (specskills_id);


--
-- Name: idx_userskills_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_userskills_user ON public.userskills_tbl USING btree (user_id);


--
-- Name: messages_tbl_conversation_id_8f182304; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX messages_tbl_conversation_id_8f182304 ON public.messages_tbl USING btree (conversation_id);


--
-- Name: messages_tbl_sender_id_e451b69f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX messages_tbl_sender_id_e451b69f ON public.messages_tbl USING btree (sender_id);


--
-- Name: reports_tbl_reported_user_id_0849887c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_tbl_reported_user_id_0849887c ON public.reports_tbl USING btree (reported_user_id);


--
-- Name: reports_tbl_reporter_id_cd20f039; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_tbl_reporter_id_cd20f039 ON public.reports_tbl USING btree (reporter_id);


--
-- Name: reports_tbl_tradereq_id_1335698c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reports_tbl_tradereq_id_1335698c ON public.reports_tbl USING btree (tradereq_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_tbl trg_sync_is_verified_from_status; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_sync_is_verified_from_status BEFORE INSERT OR UPDATE OF verification_status ON public.users_tbl FOR EACH ROW EXECUTE FUNCTION public.sync_is_verified_from_status();


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conversations_tbl conversations_tbl_requester_id_7b9c70b6_fk_users_tbl_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations_tbl
    ADD CONSTRAINT conversations_tbl_requester_id_7b9c70b6_fk_users_tbl_user_id FOREIGN KEY (requester_id) REFERENCES public.users_tbl(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conversations_tbl conversations_tbl_responder_id_4d0fae4d_fk_users_tbl_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations_tbl
    ADD CONSTRAINT conversations_tbl_responder_id_4d0fae4d_fk_users_tbl_user_id FOREIGN KEY (responder_id) REFERENCES public.users_tbl(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: conversations_tbl conversations_tbl_tradereq_id_b2e37107_fk_tradereq_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations_tbl
    ADD CONSTRAINT conversations_tbl_tradereq_id_b2e37107_fk_tradereq_ FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: password_reset_token_tbl fk_password_reset_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_token_tbl
    ADD CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id) ON DELETE CASCADE;


--
-- Name: trade_interests_tbl fk_trade_interest_trade_request; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_interests_tbl
    ADD CONSTRAINT fk_trade_interest_trade_request FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id) ON DELETE CASCADE;


--
-- Name: trade_interests_tbl fk_trade_interest_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_interests_tbl
    ADD CONSTRAINT fk_trade_interest_user FOREIGN KEY (interested_user_id) REFERENCES public.users_tbl(user_id) ON DELETE CASCADE;


--
-- Name: trade_details_tbl fk_trade_request; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_details_tbl
    ADD CONSTRAINT fk_trade_request FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id) ON DELETE CASCADE;


--
-- Name: evaluation_tbl fk_trade_request; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_tbl
    ADD CONSTRAINT fk_trade_request FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id) ON DELETE CASCADE;


--
-- Name: trade_details_tbl fk_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trade_details_tbl
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id) ON DELETE CASCADE;


--
-- Name: userskills_tbl fk_userskills_spec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl
    ADD CONSTRAINT fk_userskills_spec FOREIGN KEY (specskills_id) REFERENCES public.specskills_tbl(specskills_id) ON DELETE RESTRICT;


--
-- Name: userskills_tbl fk_userskills_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl
    ADD CONSTRAINT fk_userskills_user FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id) ON DELETE CASCADE;


--
-- Name: messages_tbl messages_tbl_conversation_id_8f182304_fk_conversat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages_tbl
    ADD CONSTRAINT messages_tbl_conversation_id_8f182304_fk_conversat FOREIGN KEY (conversation_id) REFERENCES public.conversations_tbl(conversation_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: messages_tbl messages_tbl_sender_id_e451b69f_fk_users_tbl_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages_tbl
    ADD CONSTRAINT messages_tbl_sender_id_e451b69f_fk_users_tbl_user_id FOREIGN KEY (sender_id) REFERENCES public.users_tbl(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_tbl reports_tbl_reported_user_id_0849887c_fk_users_tbl_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_tbl
    ADD CONSTRAINT reports_tbl_reported_user_id_0849887c_fk_users_tbl_user_id FOREIGN KEY (reported_user_id) REFERENCES public.users_tbl(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_tbl reports_tbl_reporter_id_cd20f039_fk_users_tbl_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_tbl
    ADD CONSTRAINT reports_tbl_reporter_id_cd20f039_fk_users_tbl_user_id FOREIGN KEY (reporter_id) REFERENCES public.users_tbl(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_tbl reports_tbl_tradereq_id_1335698c_fk_tradereq_tbl_tradereq_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_tbl
    ADD CONSTRAINT reports_tbl_tradereq_id_1335698c_fk_tradereq_tbl_tradereq_id FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: repsys_tbl repsys_tbl_tradereq_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repsys_tbl
    ADD CONSTRAINT repsys_tbl_tradereq_id_fkey FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id);


--
-- Name: specskills_tbl specskills_tbl_genskills_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specskills_tbl
    ADD CONSTRAINT specskills_tbl_genskills_id_fkey FOREIGN KEY (genskills_id) REFERENCES public.genskills_tbl(genskills_id);


--
-- Name: supptix_tbl supptix_tbl_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supptix_tbl
    ADD CONSTRAINT supptix_tbl_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_tbl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_tbl FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tradehis_tbl tradehis_tbl_tradereq_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradehis_tbl
    ADD CONSTRAINT tradehis_tbl_tradereq_id_fkey FOREIGN KEY (tradereq_id) REFERENCES public.tradereq_tbl(tradereq_id);


--
-- Name: tradereq_tbl tradereq_tbl_requester_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradereq_tbl
    ADD CONSTRAINT tradereq_tbl_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.users_tbl(user_id);


--
-- Name: tradereq_tbl tradereq_tbl_responder_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tradereq_tbl
    ADD CONSTRAINT tradereq_tbl_responder_id_fkey FOREIGN KEY (responder_id) REFERENCES public.users_tbl(user_id);


--
-- Name: usercredentials_tbl usercerts_tbl_genskills_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usercredentials_tbl
    ADD CONSTRAINT usercerts_tbl_genskills_id_fkey FOREIGN KEY (genskills_id) REFERENCES public.genskills_tbl(genskills_id);


--
-- Name: usercredentials_tbl usercerts_tbl_specskills_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usercredentials_tbl
    ADD CONSTRAINT usercerts_tbl_specskills_id_fkey FOREIGN KEY (specskills_id) REFERENCES public.specskills_tbl(specskills_id);


--
-- Name: usercredentials_tbl usercerts_tbl_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usercredentials_tbl
    ADD CONSTRAINT usercerts_tbl_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id);


--
-- Name: userinterests_tbl userinterests_tbl_genskills_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterests_tbl
    ADD CONSTRAINT userinterests_tbl_genskills_id_fkey FOREIGN KEY (genskills_id) REFERENCES public.genskills_tbl(genskills_id) ON DELETE CASCADE;


--
-- Name: userinterests_tbl userinterests_tbl_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterests_tbl
    ADD CONSTRAINT userinterests_tbl_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id) ON DELETE CASCADE;


--
-- Name: userskills_tbl userskills_tbl_specskills_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl
    ADD CONSTRAINT userskills_tbl_specskills_id_fkey FOREIGN KEY (specskills_id) REFERENCES public.specskills_tbl(specskills_id);


--
-- Name: userskills_tbl userskills_tbl_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userskills_tbl
    ADD CONSTRAINT userskills_tbl_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_tbl(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict zSO8M3vyU612OsLEH32xf7dgYrr2RWa2QUplclEJK4V1YAqoJUbaVm00jf8nyAe

