export const CATEGORIES = [
  "Creative & Design",
  "Technical & IT",
  "Business & Management",
  "Communication & Interpersonal",
  "Health & Wellness",
  "Education & Training",
  "Home & Lifestyle",
  "Handiwork & Maintenance",
  "Digital & Social Media",
  "Language & Translation",
  "Financial & Accounting",
  "Sports & Fitness",
  "Arts & Performance",
  "Culture & Diversity",
  "Research & Critical Thinking",
]